import { TutorialCard } from '../ui/TutorialOverlay';

export type TutorialStepId =
  | 'welcome' | 'flight' | 'boost' | 'target' | 'guns' | 'seekers'
  | 'shield' | 'hull' | 'repair' | 'missile-dodge' | 'cloak' | 'cloak-break' | 'emp'
  | 'mine' | 'loadout-open' | 'craft' | 'loadout-close'
  | 'trade-open' | 'trade' | 'trade-close' | 'planet' | 'surface-flight'
  | 'surface-turret' | 'surface-stash' | 'lift' | 'jump' | 'complete';

export function tutorialCards(touch: boolean): TutorialCard[] {
  const key = (desktop: string, mobile: string): string => touch ? mobile : desktop;
  return [
    { id: 'welcome', chapter: 'Flight school', title: 'Welcome, pilot', narration: 'I am Lyra, your flight instructor. This is a live training flight through the Drift. Safeties are active, and I will hold time whenever a lesson needs your full attention. Use Left and Right Arrow to revisit any lesson; touch pilots can use the chevrons.', objective: 'Continue when you are ready to take the controls.', controls: [key('Enter', 'Tap continue'), key('← / → lessons', '‹ / › lessons')], frozen: true, continueLabel: 'Begin training' },
    { id: 'flight', chapter: 'Flight', title: 'Six-axis movement', narration: 'Your ship carries momentum. The cyan nav point lies beyond a dense asteroid field, so combine thrust, strafe, lift, and roll to weave through the debris and reach it.', objective: 'Navigate through the asteroid field and reach the offset gate.', controls: [key('W A S D', 'Move stick'), key('Space / Ctrl', 'Up / Down'), key('Q / E', 'Roll')], focus: '.nav-marker' },
    { id: 'boost', chapter: 'Flight', title: 'Boost reserve', narration: 'Boost trades a rechargeable purple reserve for a burst of speed. Save some for missile evasion and disengaging from a bad fight.', objective: 'Accelerate forward and engage boost once.', controls: [key('W + Shift', 'Move + Boost')], focus: '.hud-drive', liveReview: true, review: { narration: 'Boost confirmed. The purple reserve drains only while boosting and begins refilling as soon as you release it.', objective: 'Keep flying and boosting for as long as you want, then continue to targeting.', continueLabel: 'Begin targeting' } },
    { id: 'target', chapter: 'Targeting', title: 'Read the battlespace', narration: 'Your view steers the targeting reticle. Hold it over a contact to identify the ship, its allegiance, and its range. In combat, nearby threats receive gentle aim assistance; sensors retain identified contacts through cover.', objective: 'Turn until the training contact is selected.', controls: [key('Mouse', 'Aim stick')], focus: '.crosshair', review: { narration: 'Contact identified. The wireframe, allegiance, and range readout now describe the selected ship.', objective: 'Keep the contact selected, then fire the primary weapon when ready.' } },
    { id: 'guns', chapter: 'Weapons', title: 'Primary batteries', narration: 'Primary weapons draw from the cyan energy bank, which recharges automatically. Range colour tells you whether your bolts can reach the selected contact.', objective: 'Hit the training contact with your primary weapon.', controls: [key('Left mouse', 'Fire')], focus: '.hud-weapons', review: { narration: 'Primary impact confirmed. The contact health display records the damage while your cyan weapon-energy bank recovers.' } },
    { id: 'seekers', chapter: 'Weapons', title: 'Seeker missiles', narration: 'Seekers are finite, hard-hitting ordnance. Keep a hostile selected, launch, then watch the missile fly all the way to its target.', objective: 'Launch one seeker and wait for that missile to hit the training contact.', controls: [key('Right mouse', 'Seek')], focus: '.missile-status', review: { narration: 'Seeker impact confirmed. The launched missile reached the contact, consumed one round, and left your own shields untouched.', objective: 'Begin the controlled shield-impact demonstration when ready.', continueLabel: 'Begin shield test' } },
    { id: 'shield', chapter: 'Survival', title: 'Shield impact', narration: 'After this briefing, the marked battery will fire one controlled shot. Watch the bolt arrive: your blue shield absorbs it, and the impact hemisphere reveals the direction of attack.', objective: 'Hold position and observe the incoming shield hit.', controls: ['Observe'], focus: '.hud-vitals', review: { narration: 'Shield impact confirmed. The blue loss and directional flare identify both the damage and its origin.', objective: 'Lower shields when you are ready for the hull-impact demonstration.', continueLabel: 'Lower shields' } },
    { id: 'hull', chapter: 'Survival', title: 'Hull breach', narration: 'Shields are now offline. After this briefing, the battery will fire again; this impact reaches the green hull and produces much stronger camera feedback.', objective: 'Hold position and observe the incoming hull hit.', controls: ['Observe'], focus: '.hud-vitals' },
    { id: 'repair', chapter: 'Survival', title: 'Nanobot repair', narration: 'Nanobot kits are crafted or bought, then consumed in flight. This course has issued one kit.', objective: 'Activate the nanobot kit to repair your hull.', controls: [key('H', 'Repair')], focus: '.hud-kit', review: { narration: 'Repair swarm complete. The restored green hull bar shows your repaired plating; nanobot kits are consumed on use.' } },
    { id: 'missile-dodge', chapter: 'Survival', title: 'Seeker evasion', narration: 'A training seeker is inbound. The warning counts only missiles actually tracking you and becomes urgent inside two seconds. Strafe hard across its approach; boost can widen the miss.', objective: 'Dodge the incoming seeker with lateral or vertical movement.', controls: [key('A / D / Space / Ctrl', 'Move stick / Up / Down')], focus: '.missile-warning', review: { narration: 'The seeker has lost its intercept and the lock warning is clear.', objective: 'Turn toward the marked sentry to begin cloak infiltration.' } },
    { id: 'cloak', chapter: 'Systems', title: 'Cloak infiltration', narration: 'The sentry tracks and fires while it can see you. Engage cloak, then fly close enough to pass its sensors unnoticed. Training energy is unlimited for this drill.', objective: 'Cloak and approach within 65 metres of the marked sentry.', controls: [key('F + flight controls', 'Cloak + Move')], focus: '.hud-kit', liveReview: true, review: { narration: 'The sentry lost you at close range. Training keeps energy full; in a real flight cloak drains the finite weapon bank and collapses when it runs dry.', objective: 'Move around under cloak, or fire when ready to reveal yourself.' } },
    { id: 'cloak-break', chapter: 'Systems', title: 'Weapons break cloak', narration: 'Firing reveals you immediately. Cloak is an escape tool, not a free opening volley.', objective: 'Fire once to break cloak.', controls: [key('Left mouse', 'Fire')], focus: '.hud-kit', review: { narration: 'Cloak broken. The shot and returning sentry fire confirm that weapons reveal your position.', objective: 'Begin the EMP drill when ready.', continueLabel: 'Begin EMP drill' } },
    { id: 'emp', chapter: 'Systems', title: 'EMP burst', narration: 'This training hostile is firing safely past your hull. EMP disables every hostile within 250 metres for four seconds.', objective: 'Watch its harmless gunfire, then stop it with EMP.', controls: [key('G', 'EMP')], focus: '.hud-kit', liveReview: true, review: { narration: 'EMP confirmed. The hostile is disabled for four seconds, then resumes harmless fire. Your training EMP recharges instantly, so try it again as often as needed.', objective: 'Try EMP again, or fire when ready to begin salvage.' } },
    { id: 'mine', chapter: 'Salvage', title: 'Mine exposed veins', narration: 'Bright mineral veins turn with their host asteroid. Aim at the exposed crystals, not the surrounding rock, to fracture the vein and release salvage.', objective: 'Shoot the marked vein until salvage is released.', controls: [key('Aim + left mouse', 'Aim + Fire')], focus: '.hud-resources', review: { narration: 'Vein depleted. Collect the released salvage for repairs, ordnance, trade, and ship upgrades.' } },
    { id: 'loadout-open', chapter: 'Engineering', title: 'Field engineering', narration: 'The engineering bay converts salvage into repairs, ordnance, and ship upgrades. Opening it holds your ship in place, but hostiles within 180 metres will lock it out.', objective: 'Open the Engineering loadout.', controls: [key('Tab', 'Load')], focus: '.hud-resources' },
    { id: 'craft', chapter: 'Engineering', title: 'Fabricate an upgrade', narration: 'Recipes show their exact costs and whether your current hull can use the result. Training materials have been supplied.', objective: 'Craft any available recipe.', controls: [key('Click a recipe', 'Tap a recipe')], focus: '.loadout-panel' },
    { id: 'loadout-close', chapter: 'Engineering', title: 'Return to flight', narration: 'Field upgrades serve for the current expedition. Legacy upgrades are permanent improvements fitted in the Hangar.', objective: 'Close Engineering and return to flight.', controls: [key('Tab or Esc', 'Close')], focus: '.loadout-panel' },
    { id: 'trade-open', chapter: 'Exploration', title: 'Independent merchants', narration: 'Green-beacon haulers trade supplies and remain neutral. Other civilian haulers may offer contracts when hailed.', objective: 'Dock with the marked merchant.', controls: [key('R', 'Use')], focus: '.crosshair', liveReview: true },
    { id: 'trade', chapter: 'Exploration', title: 'Trade', narration: 'Buy what the expedition needs or sell excess salvage. Your engines fall silent while docked.', objective: 'Complete any available trade.', controls: [key('Click buy or sell', 'Tap buy or sell')], focus: '.trade-panel' },
    { id: 'trade-close', chapter: 'Exploration', title: 'Undock', narration: 'The merchant survives in the sector while you explore. You can return whenever you have more salvage.', objective: 'Close Trade and return to flight.', controls: [key('R or Esc', 'Close')], focus: '.trade-panel' },
    { id: 'planet', chapter: 'Planetfall', title: 'Atmospheric entry', narration: 'Planetary sites hide bases, caves, salvage, and grounded Vigil batteries. What you destroy or recover remains changed when you return.', objective: 'Hold the jump control while aiming at the marked planet.', controls: [key('Hold J', 'Hold Jump')], focus: '.hud-drive' },
    { id: 'surface-flight', chapter: 'Planetfall', title: 'Surface navigation', narration: 'Training safeties have disabled every hostile on this site. The nav point marks one Vigil base containing both your training battery and salvage cache.', objective: 'Fly to within 105 metres of the marked enemy base.', controls: [key('Flight controls + Shift', 'Move + Aim + Boost')], focus: '.radar-wrap' },
    { id: 'surface-turret', chapter: 'Planetfall', title: 'Clear the battery', narration: 'The battery inside this base is now a passive target. It will track but not fire during training. Terrain and structures can still shield it from your fire.', objective: 'Destroy the marked battery inside the base.', controls: [key('Aim + left mouse', 'Aim + Fire')], focus: '.crosshair' },
    { id: 'surface-stash', chapter: 'Planetfall', title: 'Raid the cache', narration: 'The same base contains an armored salvage cache. Break through its outer shell to release the resources secured inside.', objective: 'Break open the marked cache inside the base.', controls: [key('Aim + left mouse', 'Aim + Fire')], focus: '.hud-resources', liveReview: true, review: { narration: 'The cache released salvage. Fly through the coloured pickups to transfer them into your hold.', objective: 'Collect what you want, then point the ship clearly skyward.' } },
    { id: 'lift', chapter: 'Planetfall', title: 'Return to orbit', narration: 'Lift-off uses the same drive, but only when your nose points clearly skyward.', objective: 'Hold the jump control to lift off.', controls: [key('Hold J', 'Hold Jump')], focus: '.hud-drive' },
    { id: 'jump', chapter: 'The Drift', title: 'Sector jump', narration: 'Deep-space jumps consume two Flux Cores. Farther sectors bring unfamiliar skies and tougher opposition; alert rises as the Vigil traces your passage.', objective: 'Hold the jump control along the clear jump vector.', controls: [key('Hold J', 'Hold Jump')], focus: '.hud-drive', liveReview: true, review: { narration: 'Arrival complete. Navigation contacts are online, and the Vigil alert has risen with your arrival.', objective: 'Look around the new sector, then view the course debrief.', continueLabel: 'View debrief' } },
    { id: 'complete', chapter: 'Course complete', title: 'You are flight-ready', narration: 'You have flown, fought, evaded missiles, survived, mined, crafted, traded, raided a base, landed, and jumped. The Drift also holds contracts, caves, wrecks, hunters, and capital ships. Choose your hull and chart your own course.', objective: 'Return to the Hangar and begin your first expedition when ready.', controls: [key('Enter', 'Tap return')], frozen: true, continueLabel: 'Return to hangar' },
  ];
}
