import { Vector3 } from 'three';
import { MissileThreat } from '../combat/ProjectileSystem';
import { Targeting } from '../combat/Targeting';
import { WeaponSystem } from '../combat/WeaponSystem';
import { Input, InputControlGate } from '../core/Input';
import { EnemyShip } from '../entities/EnemyShip';
import { NeutralShip } from '../entities/NeutralShip';
import { PlayerShip } from '../entities/PlayerShip';
import { ChaseCamera } from '../rendering/ChaseCamera';
import { AsteroidBody } from '../world/AsteroidField';
import { PlanetSurface } from '../world/PlanetSurface';
import { PlanetInfo } from '../world/Sector';
import { DeviceSystem } from './Devices';
import { Inventory } from './Inventory';
import { NavigationDestination } from './NavigationSystem';
import { TutorialSurfaceTargets } from './TutorialSurfaceMission';

export interface TutorialHost {
  readonly state: string;
  readonly player: PlayerShip;
  readonly input: Input;
  readonly touchControlsEnabled: boolean;
  readonly chaseCam: ChaseCamera;
  readonly targeting: Targeting;
  readonly weapons: WeaponSystem;
  readonly inventory: Inventory;
  readonly devices: DeviceSystem;
  readonly neutrals: readonly NeutralShip[];
  readonly worldBodies: readonly AsteroidBody[];
  readonly planets: readonly PlanetInfo[];
  readonly surface: PlanetSurface | null;
  readonly sectorIndex: number;
  spawnTrainingTarget(position: Vector3): EnemyShip;
  removeTrainingTarget(target: EnemyShip): void;
  fireTrainingBurst(target: EnemyShip): void;
  fireTrainingHit(target: EnemyShip, damage: number): void;
  fireTrainingSeeker(target: EnemyShip): void;
  playerSeekerImpacts(target: EnemyShip): number;
  releaseTrainingSeekers(): number;
  incomingMissileThreat(): Readonly<MissileThreat>;
  prepareSurfaceMission(): TutorialSurfaceTargets | null;
  setTutorialControls(gate: InputControlGate | null, preserveHeld?: boolean): void;
  stageTutorialScene(scene: 'flight' | 'loadout' | 'trade' | 'surface'): void;
  setTutorialCloak(active: boolean): void;
  setTutorialFreeze(frozen: boolean): void;
  setTutorialNavigation(destination: NavigationDestination | null): void;
  releaseTutorialNavigation(): void;
  exitTutorial(): void;
}
